# Generated by Django 6.0.2 on 2026-02-05 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCeneval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_actual', models.PositiveSmallIntegerField(default=1)),
                ('completo', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('U', 'Unión libre')], max_length=1)),
                ('calle', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('numero_interior', models.CharField(blank=True, max_length=10)),
                ('entidad_federativa', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono_personal', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registro.registroceneval')),
            ],
        ),
    ]
