# Generated by Django 6.0.2 on 2026-02-05 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque2Trayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_institucion', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=10)),
                ('regimen', models.CharField(choices=[('federal', 'Federal'), ('estatal', 'Estatal'), ('autonoma', 'Autónoma'), ('particular', 'Particular')], max_length=15)),
                ('bachillerato', models.CharField(choices=[('general', 'General'), ('tecnologico', 'Tecnológico'), ('tecnico', 'Técnico profesional')], max_length=15)),
                ('area', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('mixto', 'Mixto')], max_length=10)),
                ('promedio', models.CharField(choices=[('6-7', '6 a 7'), ('7-8', '7 a 8'), ('8-9', '8 a 9'), ('9-10', '9 a 10')], max_length=5)),
                ('beca', models.BooleanField()),
                ('motivo_beca', models.CharField(blank=True, max_length=100)),
                ('nivel_estudios', models.CharField(choices=[('tecnico', 'Técnico'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=15)),
                ('importancia_estudiar', models.CharField(choices=[('muy', 'Muy importante'), ('media', 'Importante'), ('poca', 'Poco importante')], max_length=10)),
                ('planeacion', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('colaboracion', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('comparte_info', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('escucha', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('ayuda', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('cumple', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('propone', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('conflictos', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
