# Generated by Django 6.0.2 on 2026-02-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_bloque2trayectoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='acceso_tecnologia',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='apoyo_familiar',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='asiste_clases',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='dificultades_academicas',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='dificultades_economicas',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='entrega_tiempo',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='espacio_estudio',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='estudio_independiente',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='investigacion',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='motivo_continuar',
            field=models.CharField(default=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='organizacion_material',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='perseverancia',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='primera_generacion',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloque2trayectoria',
            name='repaso',
            field=models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='beca',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')]),
        ),
    ]
