# Generated by Django 6.0.2 on 2026-02-05 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_bloque2trayectoria_acceso_tecnologia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque3CaracteristicasEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertenencia', models.CharField(choices=[('totalmente_acuerdo', 'Totalmente de acuerdo'), ('de_acuerdo', 'De acuerdo'), ('ni', 'Ni de acuerdo ni en desacuerdo'), ('en_desacuerdo', 'En desacuerdo'), ('totalmente_desacuerdo', 'Totalmente en desacuerdo')], max_length=25)),
                ('integracion', models.CharField(choices=[('totalmente_acuerdo', 'Totalmente de acuerdo'), ('de_acuerdo', 'De acuerdo'), ('ni', 'Ni de acuerdo ni en desacuerdo'), ('en_desacuerdo', 'En desacuerdo'), ('totalmente_desacuerdo', 'Totalmente en desacuerdo')], max_length=25)),
                ('aceptacion', models.CharField(choices=[('totalmente_acuerdo', 'Totalmente de acuerdo'), ('de_acuerdo', 'De acuerdo'), ('ni', 'Ni de acuerdo ni en desacuerdo'), ('en_desacuerdo', 'En desacuerdo'), ('totalmente_desacuerdo', 'Totalmente en desacuerdo')], max_length=25)),
                ('valores_compartidos', models.CharField(choices=[('totalmente_acuerdo', 'Totalmente de acuerdo'), ('de_acuerdo', 'De acuerdo'), ('ni', 'Ni de acuerdo ni en desacuerdo'), ('en_desacuerdo', 'En desacuerdo'), ('totalmente_desacuerdo', 'Totalmente en desacuerdo')], max_length=25)),
                ('apoyo_escolar', models.CharField(choices=[('totalmente_acuerdo', 'Totalmente de acuerdo'), ('de_acuerdo', 'De acuerdo'), ('ni', 'Ni de acuerdo ni en desacuerdo'), ('en_desacuerdo', 'En desacuerdo'), ('totalmente_desacuerdo', 'Totalmente en desacuerdo')], max_length=25)),
                ('respeto_docente', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('trato_justo', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('explicacion_clara', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('preparacion_docente', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('dominio_tema', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('resolucion_dudas', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('retroalimentacion', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('motivacion_docente', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('seguimiento_academico', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'Algunas veces'), ('nunca', 'Nunca')], max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
