# Generated by Django 6.0.2 on 2026-02-05 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_bloque3caracteristicasescuela'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque4EntornoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajo', models.CharField(choices=[('0', 'No trabajo'), ('1_10', 'De 1 a 10 horas'), ('11_20', 'De 11 a 20 horas'), ('21_30', 'De 21 a 30 horas'), ('31_40', 'De 31 a 40 horas'), ('mas_40', 'Más de 40 horas')], max_length=10)),
                ('estudios_jefe_hogar', models.CharField(choices=[('ninguno', 'Sin estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado')], max_length=20)),
                ('estudios_madre', models.CharField(choices=[('ninguno', 'Sin estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado')], max_length=20)),
                ('estudios_padre', models.CharField(choices=[('ninguno', 'Sin estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado')], max_length=20)),
                ('libros_en_casa', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4_mas', '4 o más')], max_length=10)),
                ('nivel_educativo_esperado', models.CharField(choices=[('ninguno', 'Sin estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado')], max_length=20)),
                ('personas_trabajando', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4_mas', '4 o más')], max_length=10)),
                ('computadora', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('televisor', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('automovil', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('banos_completos', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4_mas', '4 o más')], max_length=10)),
                ('celular_inteligente', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('internet', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('cuartos_dormir', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4_mas', '4 o más')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
