# Generated by Django 6.0.2 on 2026-02-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_bloque4entornosocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='automovil',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='banos_completos',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4_mas', '4 o más')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='celular_inteligente',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='computadora',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='cuartos_dormir',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4_mas', '4 o más')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='internet',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque4entornosocial',
            name='televisor',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
    ]
