# Generated by Django 6.0.2 on 2026-02-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_bloque4entornosocial_automovil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='beca',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
    ]
