# Generated by Django 6.0.2 on 2026-02-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_bloque2trayectoria_beca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='acceso_tecnologia',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='apoyo_familiar',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='dificultades_academicas',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='dificultades_economicas',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='espacio_estudio',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='bloque2trayectoria',
            name='primera_generacion',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True),
        ),
    ]
